config/routes.rb
# rubocop:disable Metrics/LineLength
# == Route Map
#
#                   Prefix Verb   URI Pattern                              Controller#Action
#            volume_issues GET    /volumes/:volume_id/issues(.:format)     issues#index
#             volume_issue GET    /volumes/:volume_id/issues/:id(.:format) issues#show
#                  volumes GET    /volumes(.:format)                       volumes#index
#                   volume GET    /volumes/:id(.:format)                   volumes#show
#                  library GET    /my_library(.:format)                    libraries#show
#                libraries POST   /libraries(.:format)                     libraries#create
#                          DELETE /libraries(.:format)                     libraries#destroy
#         new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
#            user_password POST   /users/password(.:format)                devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)            devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
#                          PATCH  /users/password(.:format)                devise/passwords#update
#                          PUT    /users/password(.:format)                devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PATCH  /users(.:format)                         devise/registrations#update
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)            devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format)        devise/confirmations#new
#                          GET    /users/confirmation(.:format)            devise/confirmations#show
#                     root GET    /                                        libraries#show
#
# rubocop:enable Metrics/LineLength

Rails.application.routes.draw do
  resources :volumes, only: [:index, :show] do
    resources :issues, only: [:index, :show]
  end

  get "my_library", to: "libraries#show", as: :library
  get "my_library/unread", to: "libraries#unread", as: :unread_library
  resource :libraries, only: [:create, :destroy]

  resource :readlists, only: [:create, :destroy]

  devise_for :users

  root "libraries#show"
end

app/models/volume.rb
# == Schema Information
#
# Table name: volumes
#
#  id              :integer          not null, primary key
#  comicvineid     :integer
#  name            :string
#  start_year      :integer
#  api_detail_url  :string
#  site_detail_url :string
#  image_url       :string
#  publisher_name  :string
#  description     :text
#  status          :integer          default("0")
#  created_at      :datetime
#  updated_at      :datetime
#
# Indexes
#
#  index_volumes_on_comicvineid  (comicvineid)
#

class Volume < ActiveRecord::Base
  has_many :issues
  has_many :libraries

  validates :comicvineid, :name, :start_year, :image_url, :publisher_name, presence: true

  enum status: [:active, :archived]

  def self.unread(user)
    lib_table = Library.arel_table

    conditions =
        Issue.arel_table[:issue_number]
        .gt(lib_table[:last_read])
        .or(lib_table[:last_read].eq(nil))
        .and(lib_table[:user_id].eq(user.id))

    where(conditions)
      .joins(:issues, :libraries)
      .distinct
  end

  def self.create_from_api(results)
    create!(
      comicvineid: results["id"],
      name: results["name"],
      start_year: results["start_year"],
      api_detail_url: results["api_detail_url"],
      site_detail_url: results["site_detail_url"],
      image_url: "http://static.comicvine.com" + results["image"]["medium_url"],
      publisher_name: results["publisher"]["name"],
      description: results["description"],
    )
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  def index
    @volumes = Volume.order(:id).page(params[:page])
  end

  def show
    @volume = Volume.find(params[:id])
  end

  def current_user
    @current_user ||= User.where(id: super.id).includes(:volumes).first
  end
end

app/views/volumes/_volume.html.haml
.volume
  %p
    Name:
    = volume.name
  %p
    Start year:
    = volume.start_year
  %p
    Publisher:
    = volume.publisher_name
  %p
    Number of issues:
    = link_to volume.issues.count, volume_issues_path(volume)
  %p= link_to 'ComicVine details', volume.site_detail_url
  %p= image_tag volume.image_url

app/views/volumes/_volume_list.html.haml
%ul.volumes.list-group
- @volumes.each do |volume|
  %li.volume.list-group-item.list-group-item-info
    Name:
    = link_to volume.name, volume_path(volume)
    %div{id: "add-volume-#{volume.id}"}
      = button_to 'Add to My Library', libraries_path(volume: volume.id) unless current_user.has_volume?(volume)
    %div{id: "remove-volume-#{volume.id}"}
      = button_to 'Remove from My Library', libraries_path(volume: volume.id), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'loading...' } if current_user.has_volume?(volume)
      %ul.issues.list-group
        -# TODO: collection is prety bad
        = render partial: 'issues/issue_item', collection: @issues[volume.id], as: :issue if with_issues
        = paginate @issues[volume.id], param_name: "issues_page_#{volume.id}" if with_issues
= paginate @volumes

app/views/volumes/index.html.haml
%h1 Listing

= render 'volumes/volume_list', with_issues: false

app/views/volumes/show.html.haml
= render @volume